* KP --> Key Points
* `None`--> Out Image --> دي يتم استخدامها عشان لو عايز جزء معين من الصورة اعمل عليه ديتكت وديسكربشن وتم وضعها بي نون عشان احنا هنشتغل علي الصورة كلها

In [7]:
import numpy as np 
import pandas as pd 
import cv2 as cv 
import matplotlib.pyplot as plt 
import os 
os.chdir(R"D:\\AI\\AI Models\\3. OpenCV\\0- OpenCV\\Data\\Images")
image = cv.imread('image.jpg')
gray = cv.cvtColor(image,cv.COLOR_BGR2GRAY)
sift = cv.SIFT_create()
kp =sift.detect(gray)
image = cv.drawKeypoints(gray,kp,None)
image = cv.resize(image,(500,400))
cv.imshow('KeyPoints before put and detect mag & dirct',image)
#الي هنا لم يتم تحديد ديراكشن ولا ماكنتيود بتاعنا
image = cv.drawKeypoints(gray,kp,image,flags=cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
#cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS -->
# Used because put circle in any features but special size build in pixels magnitude and orientation
image = cv.resize(image,(500,400))
cv.imshow('KeyPoints after magnitude and direction',image)
#Finally Compute descriptor
sift = cv.SIFT_create()
kp1,des =sift.detectAndCompute(gray,None) #None ---> Not Need Mask
imgg = cv.drawKeypoints(gray,kp1,image)
imgg = cv.resize(imgg,(500,400))
cv.imshow("Final Key Points",imgg)
cv.waitKey(0)
cv.destroyAllWindows()
print('The Description are --> ',des)

The Description are -->  [[  2.   0.  29. ...   0.   1. 145.]
 [  7.   1.   0. ...  25.  23.   0.]
 [  3.   0.   0. ...  29.  13.   2.]
 ...
 [ 30.  34.   2. ...   0.   0.   0.]
 [  0.   0.   1. ...   0.   0.   1.]
 [ 83.   3.   0. ...   1.   0.  10.]]
